### ISSUE TITLE
Analysis Launch Error

### ISSUE THREAD

**Issue by davidlewis720** [lemieux-lab/BamQuery#5]
Hello, thank you for this great application.

My team is trying to use BamQuery for mass spectrometry data and we believe we have successfully completed the installation process. However, upon launching the application on our company's internal server for JupyterHub using the following command:

`(BQ) python3 $INSTALLDIR/opt/bamquery/BamQuery/BamQuery.py Downloads/Bam_Query_Test/Input_Test test v26_88`

We receive the following error:

Traceback (most recent call last):
  File "/Downloads/.conda/envs/BQ/lib/python3.9/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/Downloads/.conda/envs/BQ/lib/python3.9/site-packages/pandas/compat/__init__.py", line 17, in <module>
    from pandas.compat._constants import (
  File "/Downloads/.conda/envs/BQ/lib/python3.9/site-packages/pandas/compat/_constants.py", line 20, in <module>
    ISMUSL = "musl" in (sysconfig.get_config_var("HOST_GNU_TYPE") or "")
  File "/Downloads/.conda/envs/BQ/lib/python3.9/sysconfig.py", line 610, in get_config_var
    return get_config_vars().get(name)
  File "/Downloads/.conda/envs/BQ/lib/python3.9/sysconfig.py", line 559, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Downloads/.conda/envs/BQ/lib/python3.9/sysconfig.py", line 428, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Downloads/opt/bamquery/BamQuery/BamQuery.py", line 2, in <module>
    import pandas as pd
  File "/Downloads/.conda/envs/BQ/lib/python3.9/site-packages/pandas/__init__.py", line 28, in <module>
    raise ImportError(
ImportError: C extension: _sysconfigdata_x86_64_conda_cos7_linux_gnu not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext' to build the C extensions first.

We have attempted to run the prompted command `python setup.py build_ext` but it gives us another error. As you can see in the following screenshot, we have already installed pandas. 

<img width="658" alt="Screenshot 2024-06-27 at 1 11 46 PM" src="https://github.com/lemieux-lab/BamQuery/assets/174044095/1904eb36-33a3-4a98-bbc3-f6300551f6fc">

Do you have any ideas on how to solve this? We really like this app and believe it could be very useful for our work. Please let us know if we can provide any further information. Thank you in advance.

**Comment by VirginieR** [comment]
Hi David, 

Thank you for your interest in using BamQuery.
I'm sorry to hear you're encountering this problem, but I'm happy to assist. While I'm not familiar with JupyterHub, I was wondering if you could create a virtual environment within it. This is likely the easiest way to use BamQuery, as it allows you to install the necessary libraries.
To best assist you please feel free to contact me to this email: mruizcue@broadinstitute.org.

Thank you!

**Comment by davidlewis720** [comment]
Hi Dr. Cuevas,

Thank you for your help. We have solved the problem by uninstalling and reinstalling the Pandas Package within the Conda environment on JupyterHub. I will mark this issue as resolved.
